name: registry-update-workflow
on:
  workflow_dispatch:
    inputs:
      port-name:
        description: Name of the port to update
        required: true
      port-ref:
        description: SHA hash of the updated port
        required: true

concurrency: "registry_modification"

env:
  VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'
  VCPKG_FEATURE_FLAGS: manifests,binarycaching
  X_VCPKG_NUGET_ID_PREFIX: mh-vcpkg-registry

jobs:
  update:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Setup NuGet Credentials
        shell: bash
        run: >
          nuget sources add
          -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
          -storepasswordincleartext
          -name "GitHub"
          -username "${{ github.repository_owner }}"
          -password "${{ github.token }}"

      - run: ./update-registry.ps1 -PortName "${{ github.event.inputs.port-name }}" -PortRef "${{ github.event.inputs.port-ref }}"
        shell: pwsh

      - name: Make sure we can build
        run: vcpkg install ${{ github.event.inputs.port-name }} --overlay-ports "ports"

      - name: Format all manifests
        run: vcpkg format-manifest --all --x-buildin-ports-root="ports/" --x-builtin-registry-versions-dir="versions/"

      - name: Commit ports
        uses: EndBug/add-and-commit@v7.4.0
        with:
          add: 'ports/*'
          message: "Updated ports"
          push: false

      - name: Update versions
        run: vcpkg x-add-version --all --overwrite-version --verbose --x-builtin-ports-root="ports/" --x-builtin-registry-versions-dir="versions/"

      - name: Commit versions & push
        uses: EndBug/add-and-commit@v7.4.0
        with:
          add: 'ports/*'
          message: "Updated ports"
          push: true


