name: registry-update-workflow
on:
  workflow_dispatch:
    inputs:
      port-name:
        description: Name of the port to update
        required: true
      port-ref:
        description: SHA hash of the updated port
        required: true

concurrency: "registry_modification"

jobs:
  update:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Setup NuGet Credentials
        shell: bash
        run: >
          nuget sources add
          -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
          -storepasswordincleartext
          -name "GitHub"
          -username "${{ github.repository_owner }}"
          -password "${{ github.token }}"

